### ISSUE TITLE
Using views with RiotJS ?

### ISSUE THREAD

**Issue by rrigaud** [adrianklimek/views#1]
Hi, I'm trying to make an ultralight Webapp (Portfolio) with RiotJS, and Views is just exactly what I was looking for to display pictures with VanillaJS. I make "views" work alone... but I fail when I try to combine it with RiotJS... I tryed to put my JS in index.html (outside Riot Element) and inside my Riot Element, where I make a loop that displays severals <a class="image-trigger"> but it doesn't seem to work.

Maybe it's a very stupid error, or I'm not experimented enough with Javascript...

If you could help a little bit, it would be wonderful.
Thanks a lot.

**Comment by adrianklimek** [comment]
Hi, do you get any error or warning in the console?

**Comment by rrigaud** [comment]
Hi, no error message... I uploaded my actual tests here if you want :
[http://rrigaud.fr/cuervo/](http://rrigaud.fr/cuervo/)

And here : a test without RiotJS that works fine, of course :
[http://rrigaud.fr/cuervo/test.html](http://rrigaud.fr/cuervo/test.html)
Thanks for your reactivity and your help, of course.

**Comment by adrianklimek** [comment]
I think I know what is wrong, you are trying to access elements: document.querySelectorAll(".image-trigger") but they don't exist yet. You should try to execute Views inside Riot mount event handler: http://riotjs.com/guide/#how-to-use-jquery-zepto-queryselector-etc
I have never used Riot.js, but I guess your code should look like this:
```
this.on('mount', function(){
    var views = [];
    [].forEach.call(document.querySelectorAll(".image-trigger"), function(element, index) { views[index] = new Views(element); });
})
```
Let me know if it works for you.

**Comment by rrigaud** [comment]
That's it ! I tryed some "document.onload" but it didn't work and I understand now why, it's evident.
 Forgive me for wasting your time and thanks again.

And I really like your "views" because unlike most "lightbox", it doesn't require images to be loaded in source HTML document, so it's very fast to load thumbnails, and onclick, to load the full image in a box.

Blazing fast, easy to use, VanillaJS... 👍
